config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'friends#index'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  validates :first_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

         has_many :friends, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
    private

        def after_confirmation_path_for(resource_name, resource)
            sign_in(resource)
            redirect_to root_path
        end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not an authorized user" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control', placeholder: "First Name" %>
  </div>

  <div class="field form-group">
    <% form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control', placeholder: "Last Name" %>
  </div>

  <div class="field form-group">
    <% form.label :email %>
    <%= form.text_field :email, class: 'form-control', placeholder: "Email" %>
  </div>

  <div class="field form-group">
    <% form.label :phone %>
    <%= form.text_field :phone, class: 'form-control', placeholder: "Phone no." %>
  </div>

   <div class="field form-group">
    <% form.label :phone %>
    <%= form.number_field :user_id, id: :friend_user_id, class: 'form-control', value: current_user.id , type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-outline-dark"%>
  </div>
<% end %>

app/views/friends/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Friends App", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if user_signed_in?%>
          <li class="nav-item">
            <%= link_to "Add Friend", new_friend_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link"%>
          </li>
        <%else%>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link"%>
        </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/friends/edit.html.erb
<div class = 'container'>
    <h1>Editing Friend</h1><br>

    <%= render 'form', friend: @friend %>

    <%= link_to 'Show', @friend, class:"btn btn-outline-dark" %>
    <%= link_to 'Back', friends_path, class:"btn btn-outline-dark" %>
</div>

app/views/friends/index.html.erb
<div class = 'container'>

  <% if user_signed_in? %>
    <table class="table table-striped table-hover table-bordered">
      <thead class = 'table-dark'>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @friends.each do |friend| %>
          <% if friend.user == current_user%>
            <tr>
              <td><%= friend.first_name %> <%=friend.last_name %> </td>
              <td><%= friend.email %></td>
              <td><%= friend.phone %></td>
              <td><%= link_to 'Show', friend, class:"btn btn-outline-dark btn-sm" %></td>
              <td><%= link_to 'Edit', edit_friend_path(friend), class:"btn btn-outline-dark btn-sm" %></td>
              <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
            </tr>
          <%end%>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Friend', new_friend_path, class:"btn btn-outline-dark" %>  
  <%else%>
    <h1>Hello, Rails!</h1>
  <%end%>
</div>

app/views/friends/new.html.erb
<div class = 'container'>
    <h1>New Friend</h1><br>

    <%= render 'form', friend: @friend, class:"btn btn-outline-dark" %>

    <%= link_to 'Back', friends_path, class:"btn btn-outline-dark" %>
</div>

app/views/friends/show.html.erb
<div class = 'container'>

  <div class="jumbotron jumbotron-fluid">
    <h1 class="display-4">
      <%= @friend.first_name %>
      <%= @friend.last_name %>
    </h1>
    <p class="lead"><%= @friend.email %></p>
    <p class="lead"><%= @friend.phone %></p>
    <p class="lead">
      <%= link_to 'Edit', edit_friend_path(@friend),class:"btn btn-outline-dark" %>
      <%= link_to 'Back', friends_path, class:"btn btn-outline-dark" %>
    </p>
  </div>
</div>

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-primary" role="alert">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'friends/header'%><br>
    <% if notice%>
      <%= render 'layouts/alerts'%>
    <%end%>  
    <%= yield %>
  </body>
</html>